apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  AZURE_OPENAI_ENDPOINT: {{ .Values.config.azureOpenAIEndpoint | quote }}
  AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME: {{ .Values.config.azureOpenAIEmbeddingsDeploymentName | quote }}
  AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: {{ .Values.config.azureOpenAIChatDeploymentName | quote }}
  OPENAI_API_VERSION: {{ .Values.config.openAIApiVersion | quote }}
  LANGSMITH_TRACING: {{ .Values.config.langsmithTracing | quote }}
  LANGSMITH_ENDPOINT: {{ .Values.config.langsmithEndpoint | quote }}
  LANGSMITH_PROJECT: {{ .Values.config.langsmithProject | quote }}
